---
abstract: 'Extract an exported copy of a GitHub project'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Remove: 1.51
  HTTP::Online: 0.02
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: GitHub::Extract
name: GitHub-Extract
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Archive::Extract: 0.56
  File::Spec: 3.30
  File::Temp: 0.21
  File::pushd: 1.00
  HTTP::Tiny: 0.019
  IO::Socket::SSL: 1.56
  Object::Tiny: 1.01
  Params::Util: 1.00
  perl: 5.8.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/GitHub-Extract
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/GitHub-Extract
version: 0.01
